########################################################
#	  Development-Stuff
########################################################  




########################################################
#	  Options for PHP
########################################################  

function run-php
## Source: 
## Modified from this source: 
## https://stackoverflow.com/questions/16407530/how-to-get-user-confirmation-in-fish-shell

         while true
                read -l -P '''
                        ####################################################################
                        #                       PHP
                        ####################################################################
                        #
                        #
                        #
                        #      Directions: 
                        #                       After you selected the option that you
                        #                       prefer, php will run. Press ^C to go 
                        #                       back to the menu
                        ####################################################################
                        Which One? 

                        a) php -S localhost:3000
                        b) php -S 127.0.0.1:3000
                        c) php -S localhost:4000
                        d) php -S 127.0.0.1:4000
                        e) Exit the Prompt 

                ''' confirm

            switch $confirm
                        case a
                                clear
                                php -S localhost:3000

                        case b
                                clear
                                php -S 127.0.0.1:3000

                        case c
                                clear
                                php -S localhost:4000

                        case d
                                clear
                                php -S 127.0.0.1:4000

                        case e
                                clear
                                return 0
                end
          end
end







########################################################
#	  Generates boilerplates
########################################################  


function boilerplates
## Source: 
## Modified from this source: 
## https://stackoverflow.com/questions/16407530/how-to-get-user-confirmation-in-fish-shell

         while true
                read -l -P '''
####################################################################
#                       GENERATING A BOILERPLATE?
###################################################################
                       
Which One? 

Generate C
b)  Generate Python
c)  Generate Java
d)  Generate HTML
e)  Generate README.md 
f)  Generate GitHub Actions YAML File
g)  Generate Vala 
g1) Generate Vala (Functions)
g2) Generate Vala (Reading User Input)
h) Exit


                ''' confirm

            switch $confirm
                        case a
                                clear
                                sh /home/$USER/.config/fish/conf.d/c.sh
                                notify-send "Generated Boilerplate: [C]"
                                micro main.c
                                return 0

                        case b
                                clear
                                sh /home/$USER/.config/fish/conf.d/python.sh
                                notify-send "Generated Boilerplate: [PYTHON]"
                                micro main.py
                                return 0

                        case c
                                clear
                                sh /home/$USER/.config/fish/conf.d/java.sh
                                notify-send "Generated Boilerplate: [JAVA]"
                                micro main.java
                                return 0

                        case d
                                clear
                                sh /home/$USER/.config/fish/conf.d/html.sh
                                notify-send "Generated Boilerplate: [HTML]"
                                micro main.html
                                return 0


                        case e
                                clear
                                sh /home/$USER/.config/fish/conf.d/readme-md.sh
                                notify-send "Generated Boilerplate: [README.md]"
                                micro README.md
                                return 0

                        case f
                                mkdir .github
                                cd .github
                                mkdir workflows
                                cd workflows
                                touch blank.yml
                                echo """
## File generated by Senal's dotfiles

# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

                                """ >> blank.yml

                                micro blank.yml


                        case g 
                                touch main.vala
                                echo """
/******************************************
 *
 *      ------Title------
 *
 *
 *
 *
 *
 *      ------Author-----
 *
 *
 *
 *
 *
 *
 *     -----Description---
 *
 *******************************************/

void main() {
        print("hello world");
}
                                """ >> main.vala

micro main.vala




                        case g1 
                                touch main.vala
                                echo """
/******************************************
 *
 *      ------Title------
 *
 *
 *
 *
 *
 *      ------Author-----
 *
 *
 *
 *
 *
 *
 *     -----Description---
 *
 *******************************************/
void myFunction() {
        print("hello world from function");
}


void main() {
        myfunction();
}
                                """ >> main.vala

micro main.vala




                        case g2
                                touch main.vala
                                echo """
/******************************************
 *
 *      ------Title------
 *
 *
 *
 *
 *
 *      ------Author-----
 *
 *
 *
 *
 *
 *
 *     -----Description---
 *
 *******************************************/

void userInput() {
        stdout.printf (" ");
        string prompt = stdin.read_line ();
        if (prompt != null) {
                stdout.printf ("Here is what you entered:, %s!\n", prompt);
        }
}


void main() {
        print("hello world");
}
                                """ >> main.vala

micro main.vala
                        case h
                                clear
                                return 0
                end
          end
end
