cp -R awesome /home/senal/dotfiles/Debian/.config/
cp -R fish /home/senal/dotfiles/Debian/.config/
cp -R helix /home/senal/dotfiles/Debian/.config/
cp -R i3 /home/senal/dotfiles/Debian/.config/
cp -R kitty /home/senal/dotfiles/Debian/.config/
cp -R micro /home/senal/dotfiles/Debian/.config/
cp -R neofetch /home/senal/dotfiles/Debian/.config/
cp -R nitrogen /home/senal/dotfiles/Debian/.config/
cp -R nvim /home/senal/dotfiles/Debian/.config/
cp -R nwg-drawer /home/senal/dotfiles/Debian/.config/
cp -R nwg-launchers /home/senal/dotfiles/Debian/.config/
cp -R openbox /home/senal/dotfiles/Debian/.config/
cp -R picom /home/senal/dotfiles/Debian/.config/
cp -R polybar /home/senal/dotfiles/Debian/.config/
cp -R rofi /home/senal/dotfiles/Debian/.config/
cp -R sway /home/senal/dotfiles/Debian/.config/
cp -R tint2 /home/senal/dotfiles/Debian/.config/
