brew install discord
brew install fish
brew install microsoft-edge@dev
brew install google-chrome
brew install firefox
brew uninstall vscodium
brew install gh
brew install kitty
brew install micro
brew install signal
brew install watchman
brew install nvim
brew install php
brew install tabby
brew install chatgpt
brew uninstall firefox
brew install opera-gx
brew install macs-fan-control
brew install zen-browser
brew install code-server
brew install vimac